### ISSUE TITLE
url error 

### ISSUE THREAD

**Issue by croccio** [iambluedev1/cfscrape-java#1]
in sync method url is this https://kfaction.net/banlist.. is not getter the url variable

**Comment by iambluedev1** [comment]
Hi, 

can you explain your problem ? Show me your code, the context etc... because I don't understand your request. As far I know, my lib works.

**Comment by croccio** [comment]
line 55 and 61 of this file

https://github.com/iambluedev1/cfscrape-java/blob/master/src/main/java/fr/iambluedev/cfscrape/core/CfScrape.java
